### ISSUE TITLE
Featurerequest: Support for Woltlab Burning Board in Forum Auth

### ISSUE THREAD

**Issue by Centzilius** [bob7l/HawkReloaded#30]
Hey everybody,
could you please add support for [Woltlab Burning Board](http://woltlab.com) so I can connect it with the WebUI?
Thanks in advance
Centzilius

**Comment by bob7l** [comment]
I'm going to have to deny this request because there is not really anyone else interested in using it aside from you. Feel free to fork the source and modify it though.
