### ISSUE TITLE
Hawkeye username interpretation not strict enough

### ISSUE THREAD

**Issue by q220** [bob7l/HawkReloaded#31]
We recently had a few major issues where some users got rolled back when that wasn't intended. 

If I were to have a player called SomeGriefer, and i would want to roll him back.
During the defining of the player's name with /ha rollback p:<username>, hawkeye isn't strict enough on determining what players would have to be rolled back.

If i were to type down Some, it would rollback everyone who's names start with Some. Even worse, if i were to type just s, (or t which might happen if you're making mistakes with the flags) it will rollback every single user whose name starts with that character.
This functionality is very useful for doing searches, but very nasty for doing rollbacks.

My suggestion: If hawkeye is about to do a rollback, make sure to interpret the name very strictly (100% accurate), otherwise don't rollback anything at all.

**Comment by bob7l** [comment]
This is old as hell, but still an active issue. 

What i'm thinking about doing is checking the hashmap for the player-name. If the hashmap does not contain the name, attempt to find a name LIKE the entered name.

**Comment by bob7l** [comment]
Finally fixed this issue for you. I somehow managed to misinterpret you throughout this whole conversation xD... 

I also optimized the whole lookup process, so there's that. 

https://github.com/bob7l/HawkReloaded/commit/07c714b78ab6a7f1e3d423b7775a363d91e925be
