### ISSUE TITLE
Permission hawkeye.* not complete?

### ISSUE THREAD

**Issue by q220** [bob7l/HawkReloaded#39]
One of my users have the hawkeye.* permission node, but they still lack permissions for to search for item-break.

This is because the hawkeye.search.* node at https://github.com/bob7l/HawkReloaded/blob/master/plugin.yml is lacking that permission. I also noticed that it has hawkeye.search.painting-break but I dont see where this permission is used anywhere? Possibly typo? :P

**Comment by bob7l** [comment]
Not sure how i missed this issue. 

I've always assumed permission plugins treated * as a wildcard by default, but i guess that might only be permissionsEx? 

I'll update the permissions in time for the next public release.

**Comment by RoboMWM** [comment]
> I've always assumed permission plugins treated * as a wildcard by default, but i guess that might only be permissionsEx? 

Yup, that's PermissionsEx, and it breaks plugins (or used to break? idk, I don't use wildcards) that use such wildcards.

**Comment by bob7l** [comment]
Fixed in commit https://github.com/bob7l/HawkReloaded/commit/22ef0c3e02b58bebe6dd05984f7ebc52f381ea5c
