### ISSUE TITLE
Rollback doesn't support modded tile entities?

### ISSUE THREAD

**Issue by copygirl** [bob7l/HawkReloaded#45]
Hope I'm in the right place to report this. In the case of BetterStorage backpacks, they don't like not having a tile entity attached to them. Someone reported this on the [BetterStorage issue tracker](https://github.com/copygirl/BetterStorage/issues/293):

**Comment by bob7l** [comment]
HawkEye does support TileEntity rollback and does it without any issues. It also uses 100% Bukkit API and no other 3rd party dependency. 

And it's obvious the user getting these errors is using a 3rd party software - NOT bukkit. Therefor i'm not sure why he's browsing the Bukkit forums for plugins when 99.99% of them are strictly designed to run on Bukkit or Spigot.

**Comment by prodkid** [comment]
Is there a forge equivalent that does the same job as hawkeye?

**Comment by bob7l** [comment]
I have no idea to be completely honest. I highly doubt it though considering the new objects added appear to need more data rather then just randomly being placed down. I do plan to hopefully convert this to a sponge/forge plugin in the future (When sponge is fully released), but not atm. 


I don't know enough about forge to fully help out here, but i'm going to assume the new content in that mod require further information to place down the block. So i would have to create a custom logger to properly record the backpacks data and properly roll it back..

Assuming Forge assigns ID's to these new blocks, you COULD just add them to HawkEye's filter: https://github.com/bob7l/HawkReloaded/blob/master/config.yml#L91

Like i said before, you might get lucky and find a logging plugin that supports copygirl's plugin, but it's unlikely as most plugin developers are still focused on bukkit. When Sponge is fully released, i'm sure a lot more compatibility between mods will be available though.
