### ISSUE TITLE
Attempting to add sheep to the player database?

### ISSUE THREAD

**Issue by RoboMWM** [bob7l/HawkReloaded#59]
Just updated from some versions ago to 1.7.1, and found the following shortly after server startup:

```
2016-04-15 18:28:07 [ERROR] [HawkEye] Unable to add player to database: com.mysq
l.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'SHEEP' in 'fi
eld list'

**Comment by bob7l** [comment]
Update to the latest DEV build

**Comment by RoboMWM** [comment]
I compiled from source a couple hours ago, is the dev build more up-to-date?

**Comment by bob7l** [comment]
This is actually caused by https://github.com/bob7l/HawkReloaded/commit/e99a8d4e0fa1d73f1e43088b01671f266981b160

I mixed up the column with the value. I have another commit awaiting publishing to fix this.

**Comment by bob7l** [comment]
Alright i pushed a few new commits, your issue should be resolved.

**Comment by RoboMWM** [comment]
Had some other related errors spammed in console, but seems like this commit fixed it, thanks!
