### ISSUE TITLE
container-transact

### ISSUE THREAD

**Issue by seyfahni** [bob7l/HawkReloaded#60]
Even if you enable logging for all three `container-transact`, `container-insert` and `container-extract` you can search for container-transact and will not get any results.

It might be useful, if `container-transact` could be used as short-cut for `container-insert` and `container-extract`.

On the other side, if `container-transact` should be removed in the future, it would be nice to print a warning that there won't be any new logs, because they are now split into `container-insert` and `container-extract`.

Anyway, `container-transact` should be omitted from configuration.

**Comment by bob7l** [comment]
Yeah the only issue with "omitting" this old value is we'll have to hardcode it out, which really drags down the maintainability and cleanness. 

I might end up just removing it completely. The newer 1.7+ builds wont work correctly on prior databases anyways. And our datatypes all contain manually defined id's (Thank god we don't use ordinals xD).

**Comment by RoboMWM** [comment]
Are these config options replaced by `container-transaction`? If so, should I set these options to false until they're removed? (I currently have them set to true.)

**Comment by bob7l** [comment]
No the container-transaction variable is deprecated and has been replaced with container-insert and container-extract. Having container-transaction: true within the config wont change anything aside from storing the true value in memory for the container-transaction. 

I'm most likely going to completely remove container-transaction from the next update as it's been completely replaced.

**Comment by RoboMWM** [comment]
Oh ok so he's just been spelling it wrong and I somewhat misread. So `container-insert` and extract are the replacement nodes then?

**Comment by seyfahni** [comment]
Yes, they are a replacement. Sorry for spelling mistakes, I'm not a native English-speaking person.
