### ISSUE TITLE
Hawkeye web interface not logging properly

### ISSUE THREAD

**Issue by Thortuna** [bob7l/HawkReloaded#67]
Hello. We use hawkeye reloaded on our server. We seem to be having some issues with different parts of the plugin however. 

The online web interface is currently showing wrong players issuing commands and the same for chats. So if i said "Hello World" it would tell us that a different player said "Hello World". 

The same goes for commands. I was warning a player (my IGN is Thortuna) but the logs show up as a different player did it, this players name will change every time i open the web interface and search the same thing. 
https://gyazo.com/a6023ae6b57d3865fd2f2c9691934124
https://gyazo.com/e73486729c980006d05bb6faae68540e
As you can see the first one is correct in both images but the second one is wrong. Both the ID's for the log is the same but it changes what player did this every time you search it again.

**Comment by oloflarsson** [comment]
Using the latest version: http://minebuilders.me:8080/job/HawkEye-Reloaded/103/

**Comment by bob7l** [comment]
Just to clarify, this is only the web interface, right? What about /he search?

**Comment by Thortuna** [comment]
It will show wrong people taking things out of chests ingame as well. Randomly changing the name every time you /he tool the chest so no its not just the online tool it seems.

**Comment by bob7l** [comment]
Every name should be assigned a unique ID (Actually it'd throw exceptions otherwise). The only way this could be happening is if the MySQL has assigned two or more ID's to the same user.  

Does this happen every time you /he tool a chest? Or only every so often?

**Comment by Thortuna** [comment]
Everytime you do /he tool and hit a chest or a block for that matter it changes the name of the person who interacted with the object. If i am the only one who has taken anything out of the chest and i log off it will change to a currently online player instead.

**Comment by bob7l** [comment]
Fixed in https://github.com/bob7l/HawkReloaded/commit/01f7ea77ff790af04072513b065f1874a6336abe

Big thanks to @oloflarsson  for finding the issue!
