### ISSUE TITLE
Ingame /he tool logs are different depending on which side of a chest you click on.

### ISSUE THREAD

**Issue by Thortuna** [bob7l/HawkReloaded#68]
When i hawk eye a doublechest with the ingame /he tool i get different results depending on which side i /he tool. If i click on the left side it says no results found. When i click on the right side it shows me all the items in the chest which is full.

Previously it combined the two and showed you the content of the entire double chest but this is not functioning on our server atleast at the moment. This seems to be happening on Trapped chests.

Full chest:
https://gyazo.com/b4edd49fb4bbc3a9b214206b2dfc7d5d
Left side of the chest:
https://gyazo.com/36ec00aee74e93fcc0e5bd415ccc3c0f
Right side of the chest:
https://gyazo.com/5bc1334a6bc1c0bb723998a5ec1dd157

**Comment by oloflarsson** [comment]
Using the latest version: http://minebuilders.me:8080/job/HawkEye-Reloaded/103/

**Comment by bob7l** [comment]
I'll add support for double trapped chests soon (And possibly other double block).

**Comment by bob7l** [comment]
Added in https://github.com/bob7l/HawkReloaded/commit/f8f5dc6e0ded1aad8d63d1b3fbbefea3547f5ce9
